import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import { db } from "../lib/db";
import {
  findRunbooksByOrgId,
  findRunbookById,
  createRunbook,
  deleteRunbook,
} from "@operonai/db";

export const runbooksRouter = new Hono<{ Variables: { orgId: string } }>();

runbooksRouter.get("/", async (c) => {
  const orgId = c.get("orgId") as string;

  const rows = await findRunbooksByOrgId(db, orgId);

  return c.json({ runbooks: rows });
});

runbooksRouter.get("/:id", async (c) => {
  const orgId = c.get("orgId") as string;
  const id = c.req.param("id");

  const runbook = await findRunbookById(db, id, orgId);

  if (!runbook) return c.json({ error: "Runbook not found" }, 404);

  return c.json({ runbook });
});

// Note: embedding is generated by agent-service memory layer, not here.
// This creates the runbook row — agent-service fills the embedding async.

const createRunbookSchema = z.object({
  title: z.string().min(1).max(255),
  content: z.string().min(1),
  tags: z.array(z.string()).default([]),
  sourceType: z.enum(["manual", "imported", "generated"]).default("manual"),
});

runbooksRouter.post("/", zValidator("json", createRunbookSchema), async (c) => {
  const orgId = c.get("orgId") as string;
  const body = c.req.valid("json");

  // Embedding is a required DB column — we store a zero vector as placeholder.
  // Agent-service will generate and update the real embedding when it indexes runbooks.
  // 1024 dimensions to match voyage-3 model.
  const zeroEmbedding = new Array(1024).fill(0);

  const runbook = await createRunbook(db, {
    orgId,
    title: body.title,
    content: body.content,
    tags: body.tags,
    sourceType: body.sourceType,
    embedding: zeroEmbedding,
  });

  return c.json({ runbook }, 201);
});

runbooksRouter.delete("/:id", async (c) => {
  const orgId = c.get("orgId") as string;
  const id = c.req.param("id");

  const deleted = await deleteRunbook(db, id, orgId);

  if (!deleted) return c.json({ error: "Runbook not found" }, 404);

  return c.json({ success: true, id: deleted.id });
});
